### ISSUE TITLE
how to program stm32 controller and connect it to the PCB ?

### ISSUE THREAD

**Issue by noelbjohn** [ShapeLab/SwarmUI#13]

**Comment by mathieulegoc** [comment]
Hi,
Sorry we have not had time to document this part. You have to buy a ST-Link V/2 programmer, alongside with a cable (http://www.tag-connect.com/TC2030-IDC-NL) and an adapter (http://www.tag-connect.com/ARM20-CTX). You can then download ST's software (http://www.st.com/en/embedded-software/stsw-link004.html) and upload the firmware.
We will document this very soon.
Best 
Mathieu
