### ISSUE TITLE
WheelWithSlot Sizing

### ISSUE THREAD

**Issue by Sneakyp33t** [ShapeLab/SwarmUI#21]
When I open the 3D model for the wheels it says the wheel is 24.32 x 15.68mm. I know that is too large. Can you fix this or provide the proper dimensions for the wheels?

**Comment by tennisbabo** [comment]
When I open it in Solidworks, it seems to be the correct dimension: (diameter)11 x (depth) 2 mm.

**Comment by Sneakyp33t** [comment]
I am using the windows 10 3D builder program. Maybe that's the problem. Is it possible to export a file from SolidWorks that has the dimensions of each of the 3D printed parts?

**Comment by tennisbabo** [comment]
I was able to successfully import the .stl file into windows 10 3D builder program. 
Perhaps, you selected the wrong dimension? (it should be in mm)

**Comment by Sneakyp33t** [comment]
did you get 26mm for the outer diameter of the SmallBase.stl?

**Comment by tennisbabo** [comment]
No, it should be 11mm

**Comment by Sneakyp33t** [comment]
I figured it out. When I imported the wheel is defaulted to cm instead of mm. Thank you for the help.
