### ISSUE TITLE
Difference in SwarmUi Firmware and standard DLP Firmware? DLP LightCrafter 4500

### ISSUE THREAD

**Issue by DefaultGit** [ShapeLab/SwarmUI#22]
I would like to know how the zooids_projector_firmware_image.bin is different to the standard Firmware (at the time of writing DLPR350PROM_v3.1.0.bin). Can I use the standard one, and if so, what would be different?

Edit: I am excluding the patterns that are in the firmware. I.e. if I add the images to the standard Firmware, would it be different to the zooid Firmware?

**Comment by mathieulegoc** [comment]
The zooids_projector_firmware_image.bin is the standard TI firmware in which we added the pattern images to project. So if you add the images to standard firmware, you should end up with the same file.

**Comment by DefaultGit** [comment]
Ok, thanks
