### ISSUE TITLE
Gerber files and Altium files not the same revision?

### ISSUE THREAD

**Issue by DefaultGit** [ShapeLab/SwarmUI#23]
It seems to me, that the Gerber files do not match with the current Altium Files revision, or am I missing something?

<img width="375" alt="capture1" src="https://user-images.githubusercontent.com/33762472/37087318-3b06df42-21fa-11e8-8c33-ba2634c503fd.PNG">
<img width="375" alt="capture2" src="https://user-images.githubusercontent.com/33762472/37087319-3b22cdce-21fa-11e8-9f95-9a2259278aae.PNG">

**Comment by mathieulegoc** [comment]
Hi
you're right it looks like the Gerbers were not up to date, sorry about that. I just updated them.
Mathieu

**Comment by DefaultGit** [comment]
Thanks
