### ISSUE TITLE
What is the maximum count for Zooids per receiver?

### ISSUE THREAD

**Issue by coloradocale** [ShapeLab/SwarmUI#27]
Would you be able to control 350-400 off a single receiver or control multiples of 10/50/100/etc per receiver? Considering doing this as a side project for a board game that would require ~360 zooids. Thinking about using OSHPark, OSHStencils, and a diy reflow oven or going through PCBWay for complete boards.

**Comment by coloradocale** [comment]
Would following this work or would there be an upper limit? https://devzone.nordicsemi.com/f/nordic-q-a/20021/what-is-the-maximum-number-of-nrf24l01-devices-i-can-connect-to-1

**Comment by mathieulegoc** [comment]
We limited it to 10 Zooids per receiver for now, for the sake of high refresh rate. But this can be modified in the firmware if need be, at cost of performance though.

**Comment by coloradocale** [comment]
Good to know, thank you!

**Comment by coloradocale** [comment]
You can see what we are doing with the modified Zooids and SwarmUI project at https://github.com/supersurfer92/SwarmUI-BadukBots/ and https://github.com/nheyn/GoSwarm
