### ISSUE TITLE
Is there a more specific product list?

### ISSUE THREAD

**Issue by andrew-luhring** [ShapeLab/SwarmUI#3]
I'm looking at:
https://github.com/ShapeLab/SwarmUI/blob/master/Hardware/3D%20Model/v1/Swarm%20Robot%20Assembly%20Instruction.pdf

the switch, metal balls, pcb, capacitive touch circuit, and motors all seem like things that need to be specific items... like the metal balls need to be the right size obviously in order to fit in the 3d printed case...

Is there a more specific product list somewhere? Something with model numbers?

**Comment by ghost** [comment]
I would also appreciate this. I would like to price these to argue for their use in our lab.

**Comment by mathieulegoc** [comment]
Hi Andrew, hi Rohern,
all the components concerning electronics can be found here: https://github.com/ShapeLab/SwarmUI/tree/master/Hardware/PCB%20Designs/v1.2/BOM
We will make provide a more complete documentation very soon, with references to the remaining parts.

**Comment by jvayssiere** [comment]
@andrew-luhring : In the same document you are looking at, the hyperlinks near the photos at the top of the first page will take you to the specification for each part. For a link to work you may have to download the document and open it in a PDF viewer outside of your web browser.
