### ISSUE TITLE
Specifications for Construction

### ISSUE THREAD

**Issue by quintinNCAT** [ShapeLab/SwarmUI#9]
What are the specifications/dimensions  for the O-ring, metal balls (caster wheels), switch, laser cut inner lid, and laser cut outer lid? When searching through the hardware file and the instructions to build the Zooids, the specifications for those parts were not listed. Thank you and have a great day.

**Comment by jvayssiere** [comment]
It's all available from the hyperlinks near the photos in the PDF document that describes assembly.
